### PR TITLE
upgrade bundled ElixirLS release 

### LINKED ISSUE #19: elixir 1.9 breaks ide-elixir
### Is this the right repo?

This has already been fixed in ElixirLS.

https://github.com/JakeBecker/elixir-ls/issues/155

I have ide-elixir 0.2.23 (latest).

### Symptom

Immediately after updating to 1.9 this appears in the Diagnostics window:

```bash
an exception was raised:
    ** (UndefinedFunctionError) function Mix.Dep.loaded/1 is undefined or private
        (mix) Mix.Dep.loaded([])
        (language_server) lib/language_server/build.ex:16: anonymous fn/2 in ElixirLS.LanguageServer.Build.build/3
        (stdlib) timer.erl:166: :timer.tc/1
        (language_server) lib/language_server/build.ex:13: anonymous fn/2 in ElixirLS.LanguageServer.Build.build/3
        (kernel) global.erl:425: :global.trans/4
```

Also, the PLT building isn't successful, but I reckon this is because the crash above.

### PR DESCRIPTION
**Pull request by bdubaut**
This PR upgrades ElixirLS to `v0.2.25`. Should fix #19 🙏.

_It's my first time trying to improve something with Atom, can someone walk me through a way to see if this works? I assume I need to start atom and tell it to use this package?_

### CODE REVIEW

**Comment by JakeBecker** [comment]
Thank you for this! I've been neglecting this extension, thank you for picking up the slack.

In Atom, unfortunately, you can't include compiled artifacts in the extension unless you track them in the git repo. I'll compile it and add the result to the repo and publish it.

**Comment by JakeBecker** [comment]
I've just published v0.2.25 to Atom. Can you verify that it solves the problem? I use Atom so little, I'm not totally sure I tested it correctly.

**Comment by bdubaut** [comment]
@JakeBecker it seems to be working OK, from what I can see. Thanks!

**Comment by javobalazs** [comment]
I've just installed it, upgraded to elixir 1.9. The PLT building was okay, and the dialyzer_manifest got generated for the open project (only one) in .elixir_ls. I opened another project but the dialyzer_manifest just wouldn't get generated for that, and for any other project either. So there seem to be still an issue.

**Pull request merged**
